<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ciudades [
<!ELEMENT ciudades (ciudad*)>
<!ELEMENT ciudad (nombre,pais)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ATTLIST pais continente CDATA #REQUIRED>

]>


<ciudades>
 <ciudad>
    <nombre>nueva delhi</nombre>
    <pais continente="asia" >india </pais>
 </ciudad>

 <ciudad>
    <nombre>lisboa</nombre>
    <pais continente="europa" >Portugal </pais>
 </ciudad>
    
    
<ciudad>
    <nombre>el cairo </nombre>
    <pais continente="África" > Egipto </pais>
 </ciudad>

</ciudades>