<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa [
<!ELEMENT empresa (empleados)*>
<!ELEMENT empleados (primernombre,apellido+,numerocontrato,correoelectronico) >
 <!ELEMENT primernombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
 <!ELEMENT numerocontrato  (#PCDATA)>
<!ELEMENT correoelectronico (#PCDATA)>
<!ELEMENT direccion (ciudad,estado)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
]>
<empresa>
  <empleado>
       <primernombre>roberto </primernombre>  
        <apellido> vazquez </apellido>
         <numerocontrato> 123</numerocontrato>
         <correoelectronico> pepeowen@hotmail.com</correoelectronico>
         <direccion> 
              <ciudad>santander</ciudad>
              <estado>cantabria </estado> 
            <zip>39011</zip>   
          </direccion>
    </empleado>
    <empleado>
       <primernombre>alejandro </primernombre>  
        <apellido> ortiz </apellido>
         <numerocontrato> 124</numerocontrato>
         <correoelectronico> jandruco@hotmail.com</correoelectronico>
         <direccion>
              <ciudad>santander</ciudad>
              <estado>cantabria </estado> 
            <zip>39001</zip>   
          </direccion>
    </empleado> 
</empresa>