<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos [
<!ELEMENT equipos (equipo)+>
<!ELEMENT equipo (nombre,ciudad,entrenador)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT entrenador EMPTY>
<!ELEMENT jugador (nombre,nacionalidad)>
<!ATTLIST jugador posicion CDATA #REQUIRED>
<!ELEMENT nombrej (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>

]>

<equipos>
   <equipo>
      <nombre> Real de Madrid</nombre>
       <ciudad> Madrid   </ciudad>
       <entrenador/>
     <jugador posicion="delantero">
           <nombrej> CR7 </nombrej>
           <nacionalidad>Portugal</nacionalidad>
     
     </jugador>    
    </equipo>
       
    <equipo>
        <nombre> Real Racing Club </nombre>
        <ciudad> Santander  </ciudad> 
        <entrenador/>
       <jugador posicion="portero">

             <nombrej> Ivan Crespo </nombrej>
             <nacionalidad>Espa√±ol</nacionalidad>
         
       </jugador>    
    </equipo>
</equipos>