<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE hechohistorico [
     
 <!ELEMENT hechohistorico (hecho+)>
 <!ELEMENT hecho (fecha)>
 <!ATTLIST hecho descripcion CDATA #REQUIERED>
 <!ELEMENT fecha (dia,mes,ano)>
 <!ELEMENT dia (#PCDATA)>
 <!ELEMENT mes (#PCDATA)>
 <!ELEMENT ano (#PCDATA)>
 
]>

<hechohistorico>
 
    <hecho descripcion="IBM da a conocer el PC" >
        
        <fecha>
         <dia>12</dia>
         <mes>8</mes>
         <ano>1981</ano>        
        </fecha>
     
        
    
    </hecho>

 <hecho descripcion="Se funda google" >
        
        <fecha>
         <dia>4</dia>
         <mes>9</mes>
         <ano>1998</ano>        
        </fecha>
            
    
 </hecho>


 <hecho descripcion="se funda Facebook" >
        
        <fecha>
         <dia>4</dia>
         <mes>2</mes>
         <ano>2004</ano>        
        </fecha>
     
        
    
    </hecho>




</hechohistorico>