=== rober1234/moduloxml/libro.dtd
<!-- DTD de un libro --> 
<!ELEMENT libros (libro+)> 
<!ELEMENT libro (portada, cuerpo, contraportada?)> 
<!-- PORTADA --> 
<!ELEMENT portada (titulo, edicion, autor, editor)> 
<!ELEMENT titulo (#PCDATA)> 
<!ELEMENT edicion (#PCDATA)> 
<!ELEMENT autor ((nombre, apellidos, email?) | anonimo)> 
<!ELEMENT nombre (#PCDATA)> 
<!ELEMENT apellidos (#PCDATA)> 
<!ELEMENT email (#PCDATA)> 
<!ELEMENT anonimo EMPTY> 
<!ELEMENT editor (nombre, apellidos, direccion?)> 
<!ELEMENT direccion (calle, poblacion, provincia?, pais?)> 
<!ELEMENT calle (#PCDATA)> 
<!ELEMENT poblacion (#PCDATA)> 
<!ELEMENT provincia (#PCDATA)> 
<!ELEMENT pais (#PCDATA)> 
<!-- CUERPO --> 
<!ELEMENT cuerpo (parte+ | capitulo+)> 
<!ELEMENT parte (titulo, capitulo+)> 
<!ENTITY % Bloques "(parrafo | lista | codigo)*"> 
<!ELEMENT capitulo (titulo, %Bloques;, seccion*)> 
<!ELEMENT seccion (titulo, %Bloques;, sub-seccion*)> 
<!ELEMENT sub-seccion (titulo, %Bloques;)> 
<!ELEMENT parrafo (#PCDATA)> 
<!ATTLIST parrafo alinea (izq | cent | der | just) "just"> 
<!ELEMENT lista (item+)> 
<!ATTLIST lista tipo (num | rom | alpha) #REQUIRED> 
<!ELEMENT item (#PCDATA)> 
<!ELEMENT codigo (#PCDATA)> 
<!ATTLIST codigo lenguaje (c | cobol | java | vb) "c"> 
<!-- CONTRAPORTADA --> 
<!ELEMENT contraportada (glosario)> 
<!ELEMENT glosario (titulo, entrada*)> 
<!ELEMENT entrada (titulo, definicion+)> 
<!ELEMENT definicion (#PCDATA)>

=== rober1234/moduloxml/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "libro.dtd">
<libros>
   <libro>
     <portada>
         <titulo> </titulo>
         <edicion></edicion>               
    </portada>
       <autor>
        <nombre></nombre>
        <apellidos></apellidos>
         <email></email>
         <anonimo/>  
      </autor>
      <editor>
          <nombre></nombre>
          <apellidos></apellidos>
          <direccion>
               <calle></calle>
               <poblacion></poblacion>
               <provincia></provincia>
               <pais></pais>
             
         </direccion>
       
      </editor>
       
    <cuerpo >
        <parte>
            <titulo></titulo>
                        
                <capitulo> 
                     <titulo></titulo>
                      <bloques></bloques>
                    <seccion>
                        <titulo></titulo>
                         <bloque></bloque>
                            <sub_seccion>
                              <titulo></titulo>
                               <bloques></bloques>
                            </sub_seccion>
                    
                    </seccion>
                <parrafo>
                       <parrafo alinia="iz">
                            
                           
                        </parrafo>
                    
                    
                    </parrafo>   
                    
                    <lista tipo="num">
                        <item></item>
                        <codigo lenguaje="c"></codigo>
                                                            
                    </lista>
                    
                </capitulo>
             
               <contraportada>
                   
                   <glosario>
                        <titulo></titulo>
                        <entrada>
                            <titulo></titulo>
                            <definicion></definicion>
                            
                       </entrada>
                        
                     
                   
                   </glosario>
             
               </contraportada>
         
        </parte>    
         
        
        
    </cuerpo> 
    
    
    </libro>


































</libros>
