=== rober1234/moduloxml/matricula.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<xs:element name="matricula">
<xs:compexType>
 <xs:squence>
<xs:element name="personal" >
<xs:compexType>
 <xs:squence>
    <xs:element name="nombre" type="xs:string"/>
    <xs:element name="titulacion" type="xs:string"/>
    <xs:element name="curso_academico" type="xs:string"/>
    <xs:element name="domicilios">
        <xs:compexType>
        <xs:esquence>
    
        <xs:element name="domicilio" type="familiar">
             <xs:compexType>
                   <xs:esquence>
                   
                        <xs:element name="nombre" type="x:string"/>
                                            
                   <xs:element name="domicilio" type="habitual">
             <xs:compexType>
                   <xs:esquence>
                        <xs:element name="nombre" type="x:string"/>
                   </xs:esquence>      
             </xs:compexType>
        </xs:element>
        </xs:esquence>
        </xs:compexType>
       <xs:element name="pago">
           <xs:compexType>
             <xs:esquence>
                     <xs:element name="tipo_matricula"/>
                            
             </xs:esquence>           
           
           </xs:compexType>       
      
       </xs:element>
      
    </xs:element>
   </xs:squence> 
 </xs:compexType>
     
    
</xs:element>
</xs:schema>

=== rober1234/moduloxml/matricula.xml
<?xml version="1.0" encoding="UTF-8"?>
<matricula  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="matricula.xsd">
<personal>
     <dni>99223366M</dni>
     <nombre>Juan Pardo Martin</nombre>
     <titulacion>Ingenieria Informática</titulacion>
     <curso_academico>1997-1998</curso_academico>
     <domicilios>
        <domicilio tipo="familiar">
          <nombre>C/Principal n 1</nombre>        
        
        </domicilio>
         <domicilio tipo="habitual">
          <nombre>C/secundaria n 2</nombre>        
                </domicilio>
          
     </domicilios>
</personal>
<pago>

<tipo_matricula>Matrícula Ordinaria</tipo_matricula>
</pago>
</matricula>
